### ISSUE TITLE
name 'US' is not defined - enumeration bug

### ISSUE THREAD

**Issue by attilabibok** [OpenWaterAnalytics/pyswmm#272] opened 2021-02-20 15:10 UTC
Hi,

I get the "name 'US' is not defined" NameError message during importing any module from the pyswmm package.

  File "C:\Users\Bibok Attila\AppData\Local\Programs\Python\Python38\lib\site-packages\pyswmm\__init__.py", line 11, in <module>
    from pyswmm.links import Link, Links
  File "C:\Users\Bibok Attila\AppData\Local\Programs\Python\Python38\lib\site-packages\pyswmm\links.py", line 9, in <module>
    from swmm.toolkit import shared_enum
  File "C:\Users\Bibok Attila\AppData\Local\Programs\Python\Python38\lib\site-packages\swmm\toolkit\shared_enum.py", line 13, in <module>
    class UnitSystem(Enum, start=0):
  File "C:\Users\Bibok Attila\AppData\Local\Programs\Python\Python38\lib\site-packages\swmm\toolkit\shared_enum.py", line 23, in UnitSystem    US

NameError: name 'US' is not defined

It originates from the shared_enum module.

The problem can be reproduced in Win10 and version **v1.0.1** and **v1.0.0**. 
Python version 3.7 and 3.8 also throws the error.

I installed the package using "pip install pyswmm=1.01"
All requirements/ dependencies seem to be installed.

v0.6.2 works flawlessly as before.

I started to patch it up for myself locally by explicitly enumerating instead of auto, but I guess that's not in line with the purpose of introducing this auto enumeration in v1.0.0 version. I guess it should be addressed in a more elegant way.

**Comment by jennwuu** [comment] 2021-02-20 15:15
Thank you for catching this error. It will be addressed in the next release. 

In the meantime, can you use instead? 
```
from pyswmm import Links
```

**Comment by jennwuu** [comment] 2021-02-20 15:22
@attilabibok I looked into the error further. This error is caused by aenum. Can you downgrade aenum to v2.2.6? 

SWMM-toolkit does not work with v3.0.0.

**Comment by attilabibok** [comment] 2021-02-20 16:49
Thank you for the workaround. The downgrading worked.

**Closed** 2022-08-18 10:43 UTC
Labels: type:bug
