### ISSUE TITLE
Rain Gage total precipitation can´t be set correctly

### ISSUE THREAD

**Issue by tscheuch** [OpenWaterAnalytics/pyswmm#238] opened 2020-06-11 00:41 UTC
**Describe the bug**
I was trying to reset the the Rain Gage precipitation while the simulation is running and I have problems when the amount is not an integer.  

**To Reproduce**
I have two subcatchments (S1, S2) with a diferent Rain Gage (RG1, RG2) for each one. At the begining the precipitation time series are equal. The idea is that durning the simulation i need to reincorporate the evaporation from S2 to the RG2 (that is why i need to set the precipitation durning the simulation). I did some tests adding a constant value to RG2 from the original one (RG1). 
The code is: 
![image](https://user-images.githubusercontent.com/61126547/84332355-bd539800-ab5a-11ea-854e-a53d738e81d3.png)

When I plot the total precipitation:

![image](https://user-images.githubusercontent.com/61126547/84331614-a57b1480-ab58-11ea-92dd-cc0e5d2ac1ea.png)

The magnitud is the same but the curve is displaced on one Runoff Step Wet Weather.

But, if I add 1 mm/h instead of 0.5 mm/h  (p2=p1+1.0). I get:

![image](https://user-images.githubusercontent.com/61126547/84331852-5a153600-ab59-11ea-8065-e74c17d39888.png)
That is the behavior I was expecting on the first case too!

**Desktop (please complete the following information):**
 - OS: Windows
 - Python Version : Python 3.7.4
 - PySWMM Version: 0.6.0

**Comment by bemcdonnell** [comment] 2020-06-11 01:15
@tscheuch, we solved this issue recently but I don’t believe it has been merged back in. The issue is that behind the scenes in SWMM the value holding the rainfall rate is an int, not float.  Let me check where the code is. Maybe we can get it merged in tomorrow!

**Comment by bemcdonnell** [comment] 2020-06-15 19:58
@tscheuch, just so you are aware, this bug fix has been made here: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/pull/278. Let me see what we can do about getting a patch release over there so we can release PySWMM with that binary.

**Comment by tscheuch** [comment] 2020-06-24 01:16
Thank you so much @bemcdonnell! In the meantime...is there any way  that I can work locally with pyswmm with the last Stormwater-Management-Model binary?

**Comment by bemcdonnell** [comment] 2020-06-24 03:37
Which binary are you wanting to run?

**Comment by tscheuch** [comment] 2020-08-07 21:30
Hi! I just upgraded pyswmm to the 0.6.2 version and I got the same problem!

**Comment by katmratliff** [comment] 2020-08-10 11:50
@bemcdonnell @jennwuu what do you all think about a patch release of OWA-SWMM so we can incorporate those binaries? I know there's been a lot of hard work over there over the past few months, but I'm not sure what the status is in terms of being close to a release to incorporate this fix.

**Comment by bemcdonnell** [comment] 2020-08-10 11:55
@katmratliff, I’m in favor of it! @tscheuch, sorry about the bug still!

**Comment by floriandorre** [comment] 2020-10-13 15:09
Hi, does someone have a temporary fix for this issue while it is not deployed ?

**Comment by katmratliff** [comment] 2020-10-14 12:25
@jennwuu @bemcdonnell @cbuahin what do you all think about a patch release of OWA-SWMM so we can incorporate this fix into pyswmm?

**Comment by katmratliff** [comment] 2020-10-14 12:38
Hi @floriandorre a work-around for the meantime would be to to compile the current version of OWA-SWMM and use that binary with pyswmm. What operating system are you currently using?

**Comment by cbuahin** [comment] 2020-10-14 15:13
> @jennwuu @bemcdonnell @cbuahin what do you all think about a patch release of OWA-SWMM so we can incorporate this fix into pyswmm?

@katmratliff , I don't see why not but I will leave it to Bryant and Jenn.

**Comment by bemcdonnell** [comment] 2020-10-14 17:10
@katmratliff, I suggesting making the release of pyswmm-v0.6.3 (or are we on 0.6.4).  We are almost done with pyswmm-v1 but that will be in Beta for a few months

**Comment by katmratliff** [comment] 2020-10-14 17:41
Thanks @bemcdonnell. When you all make a patch release of OWA-SWMM, I can pull the binaries from that over to pyswmm and make a release here. Or let me know if you all think there's a better way to proceed. I'll be on the on the lookout at the SWMM repo, @bemcdonnell @jennwuu @cbuahin!

**Comment by bemcdonnell** [comment] 2020-10-21 18:59
@jennwuu, if I buy some food for your sloth, could you make a quick patch release with this minor bug fix?

**Comment by jennwuu** [comment] 2020-10-21 19:04
This is fixed in pyswmm v1.0 release.

**Closed** 2022-08-18 10:42 UTC
Labels: type:bug
